[FIX] stock_fleet: prevent the error when try to save without Dock Location
This error occurs when attempting to save a 'Batch Transfer' without specifying
a 'Dock Location'.

Steps to reproduce:
- Install the 'stock_fleet' module
- Activate 'Storage Locations' in Configuration of Inventory
- Now go to 'Batch Transfers' in Operations and Create new
- Now add 'Dock Location' and save
- Now Remove 'Dock Location' and save

Traceback: AttributeError
'stock.picking.batch' object has no attribute 'location_dest_id'

The error in [1] occurred because the 'location_dest_id' field is not part of
the 'stock.picking.batch' model but belongs to the 'stock.picking' model.

This commit resolves the error by adding 'picking_ids', allowing us to retrieve
the 'location_dest_id'.

[1]- https://github.com/odoo/odoo/blob/45e75693e8ee4f8cf9af842cd2facd4f2f6356d8/addons/stock_fleet/models/stock_picking_batch.py#L81

sentry-5825702049

X-original-commit: a4f403cc340899c43df3d4290212b8814946470c